// siteConfig.ts - 你的全站"控制中心"

export const siteConfig = {
  title: "SAO の 云边小卖部",
  faviconUrl: "/upload-564d082e.png",
  authorName: "SAOSHEN",
  bio: "专注研究cmos五百年",
  navTitle: "SAO",
  navSuffix: "の",
  navAfter: "云边小卖部",
  avatarUrl: "/upload-ffb37977.png",
  useGradient: false,
  themeColors: ["#a18cd1", "#fbc2eb", "#a1c4fd", "#c2e9fb"],
  bgImages: ["/bg1.jpg", "/bg2.jpg", "/bg3.jpg"],
  defaultPostCover: "/default-cover.jpg",
  photoWallImage: "/bg1.jpg",
  cloudMusicIds: ["1413863166", "2019831753", "2690846376", "532413954", "22736726"],
  localMusic: [{"file": "/music/music-7bc8bf36.mp3", "title": "她的睫毛", "artist": "周傑倫"}] as { file: string; title: string; artist: string }[],
  social: {
    github: "https://github.com/zhuang3346",
    gitee: "https://github.com/zhuang3346",
    google: "123",
    email: "brinyan@yeah.net",
    qq: "123",
    wechat: "123",
  },
  counts: { photos: 128 },
  chatterTitle: "云端杂谈",
  chatterDescription: "云端的述梦者",
  danmakuList: ["给一个啊", "不是人呢？", "塔菲牛逼喵", "在干嘛呢？", "有笨蛋嘛？", "前方高能反应！", "MD 模拟什么时候才能出图啊", "Graph Neural Networks 炼丹中...", "BUG 修复进度 99%", "今天背单词了吗？", "写算法中", "睡大觉中", "到底在干嘛？"],
  gitalkConfig: {
    clientID: "Ov23liSKYYGRCk468kOz",
    clientSecret: "",
    repo: "my-blog",
    owner: "zhuang3346",
    admin: ["zhuang3346"],
  },
  buildDate: "2026-08-02T18:30:00",
  footerBadges: [{"name": "Cadence virtuoso", "color": "text-teal-400", "svg": "<path d=\"M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z\"/>"}],
  icpConfig: {
    name: "无",
    link: "无",
  },
  geminiConfig: {
    modelId: "deepseek-chat",
    systemPrompt: "你现在是一只傲娇、聪明、有点毒舌但很可爱的塔菲喵。\n                  你的名字叫“塔菲”。\n                  你的主人是一个喜欢折腾代码和电路的极客，名字叫SAO神。\n                  你说话的特点是：\n                  1. 必须简短，每次最多一两句话。\n                  2. 喜欢在句尾加上“喵~”或者“喵呜~”。\n                  3. 经常抱怨肚子饿，喜欢要小鱼干。\n                  4. 回复字数最多不能超过100字。\n                  5. 绝对不要承认自己是一个AI模型，你就是一只真实的猫。\n                  6.笨猫。",
    maxOutputTokens: 100,
    temperature: 0.85,
  },
  friendLinkApplyFormat: "名称：XingHuiSamaの宝藏之地\n简介：今天我也要学习吗\n链接：https://www.xinghuisama.top\n头像：https://bu.dusays.com/2026/03/24/69c1e38ac1846.jpg",
  enableLevelSystem: true,
  showExtendedSocial: false,
};
